Django WaterIO/WaterIO/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from basic_app import views
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.page_one,name='page_one'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='basic_app/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='basic_app/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='basic_app/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='basic_app/password_reset_complete.html'),name='password_reset_complete'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ]+urlpatterns

Django WaterIO/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'app'

urlpatterns = [
    path('',views.page_one,name='page_one'),
    path('user_login/',views.user_login,name='user_login'),
    path('register/',views.register,name='register'),
    path('user_details/',views.user_details,name='user_details'),
    path('groundwaterlevel/',views.groundwaterlevel,name='groundwaterlevel'),
    path('ajax/load-sites/', views.load_sites, name='ajax_load_sites'),
    path('ajax/forecast/', views.model, name='ajax_forecast'),
    path('weatherforecast/',views.weatherforecast,name='weatherforecast'),
    path('addbookmark/<c>/',views.addbookmark,name='addbookmark'),
    path('deletebookmark/<c>/',views.deletebookmark,name='deletebookmark'),
]

Django WaterIO/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import pandas as pd
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    
    #Additional Features
    profile_pic = models.ImageField(default='default.jpg',upload_to='profile_pics')

    def __str__(self):
        return self.user.username

    def save(self):
        super().save()
        img = Image.open(self.profile_pic.path)
        
        if img.height>300 or img.width>300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

class GWL_inputs(models.Model):
    import os
    
    current_directory = os.getcwd()+'\\basic_app\\website_data_20190225.csv'
    current_directory = current_directory.replace('\\','/')
    ori = pd.read_csv(current_directory)

    dataset = ori['STATE'].unique()
    choices0 = []
    for i in range(0,dataset.shape[0]):
        choices0.append([dataset[i],dataset[i]])
    state = models.CharField(max_length=9, choices=choices0, default='State')

    dataset = ori['DISTRICT'].unique()
    choices1 = []
    for i in range(0,dataset.shape[0]):
        choices1.append([dataset[i],dataset[i]])
    district = models.CharField(max_length=9, choices=choices1, default='District')

    dataset = ori['BLOCK_NAME'].unique()
    choices2 = []
    for i in range(0,dataset.shape[0]):
        choices2.append([dataset[i],dataset[i]])
    block = models.CharField(max_length=9, choices=choices2, default='Block_Name', primary_key=True)

    def __str__(self):
        return self.block

class Site_Name(models.Model):
    block = models.ForeignKey(GWL_inputs, on_delete=models.CASCADE)
    site = models.CharField(max_length=15, choices=[['---','---'],], default='---')
    # site = forms.Select(choices=['---']) Choices

    def __str__(self):
        return self.site

class FYear (models.Model):
    year = models.IntegerField(validators=[MinValueValidator(2016), MaxValueValidator(2025)], default=datetime.date.today().year)

    def __str__(self):
        return self.year

class City(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'

Django WaterIO/basic_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from basic_app.models import UserProfileInfo,GWL_inputs,Site_Name,FYear,City
from basic_app.modelforms2 import UserForm,UserProfileInfoForm,UserUpdateForm,ProfileUpdateForm,GWL,Site,Year,CityForm
from django.db import models

# from basic_app.modelforms2 import UserRegisterForm
# def register(request):
#         if request.method == "POST":
#                 form = UserRegisterForm(request.POST)
#                 if form.is_valid():
#                         form.save()
#                         username = form.cleaned_data.get('username')
#                         messages.success(request,f'Account created for {username}!')
#                         return redirect('page_one')
#         else:
#                 form = UserRegisterForm()
#         return render(request,'basic_app/register.html',{'form':form})


def page_one(request):
        return render(request,'basic_app/page_one.html')

def register(request):
        registered = False
        if request.method == "POST":
                user_form = UserForm(data=request.POST)
                profile_form = UserProfileInfoForm(data=request.POST)
                if user_form.is_valid() and profile_form.is_valid():
                        user = user_form.save()
                        user.set_password(user.password)
                        user.save()
                        profile = profile_form.save(commit=False)
                        profile.user = user
                        if 'profile_pic' in request.FILES:
                                profile.profile_pic = request.FILES['profile_pic']
                        profile.save()
                        registered = True
                else:
                        print(user_form.errors,profile_form.errors)
        else:
                user_form = UserForm()
                profile_form = UserProfileInfoForm()
        return render(request,'basic_app/register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
        if request.method == 'POST':
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = authenticate(username=username,password=password)
                if user:
                        if user.is_active:
                                login(request,user)
                                print("Username: {} and Password: {}".format(username,password))
                                return HttpResponseRedirect(reverse('page_one'))
                        else:
                                return HttpResponse("Account NOT Active")
                else:
                        print("Username: {} and Password: {}".format(username,password))
                        messages.warning(request,'Invalid Login Details!')
        return render(request,'basic_app/login.html')

@login_required
def user_logout(request):
        logout(request)
        return HttpResponseRedirect(reverse('page_one'))

def user_details(request):
        from django.conf import settings
        if request.method == 'POST':
                u = UserUpdateForm(request.POST, instance=request.user)
                p = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
                if u.is_valid() and p.is_valid():
                        u.save()
                        p.save()
                        return HttpResponseRedirect(reverse('page_one'))
        else:
                u = UserUpdateForm(instance=request.user)
                p = ProfileUpdateForm(instance=request.user.profile)
        return render(request,'basic_app/userdetails.html',{'chk':UserProfileInfo.objects.all(), 'media_url':settings.MEDIA_URL, 'u_update':u, 'p_update':p})

def groundwaterlevel(request):
        # messages.get_messages(request).used = True
        # messages.success(request,'You have to login first to access it!')
        # messages.add_message(request, messages.SUCCESS, 'You have to login first to access it!')
        # messages.get_messages(request).used = False
        form1 = GWL()
        form2 = Site()
        form3 = Year()
        return render(request,'basic_app/groundwaterlevel.html',context={'form1':form1,'form2':form2,'form3':form3})

def unique(list1): 
    unique_list = [] 
    for x in list1: 
        if x not in unique_list: 
            unique_list.append(x) 
    return unique_list

def load_sites(request):
        import os
        import pandas as pd

        current_directory = os.getcwd()+'\\basic_app\\website_data_20190225.csv'
        current_directory = current_directory.replace('\\','/')
        ori = pd.read_csv(current_directory)
        block = request.GET.get('block')
        chk=[]
        for i in range(0,ori.shape[0]):
                if ori['BLOCK_NAME'][i]==block:
                        chk.append(ori['SITE_NAME'][i])
        choices3 = unique(chk)
        print(choices3)
        return render(request, 'basic_app/dropdown.html', {'sites': choices3})

def model(request):
        import numpy as np
        import pandas as pd
        import seaborn as sns
        import warnings
        warnings.filterwarnings('ignore')
        from datetime import datetime
        from statsmodels.tsa.arima_model import ARIMA
        from datetime import date
        import time
        import os
        
        current_directory = os.getcwd()+'\\basic_app\\website_data_20190225.csv'
        current_directory = current_directory.replace('\\','/')
        ori = pd.read_csv(current_directory)
        ori.drop(['STATE', 'DISTRICT', 'WLCODE', 'SITE_TYPE', 'TEH_NAME', 'LAT', 'LON'], axis=1, inplace=True)
        ori.replace(to_replace="'0", value=0, inplace=True)    

        dataset1 = pd.DataFrame().reindex_like(ori)
        dataset1.dropna(inplace=True)
        j = 0
        for i in range(0, ori.shape[0]):
                if ori['BLOCK_NAME'][i] == request.GET.get('block'):
                        dataset1.loc[j] = ori.iloc[i]
                        j += 1
        dataset1.drop(['BLOCK_NAME'], axis=1, inplace=True)
        dataset = pd.DataFrame().reindex_like(dataset1)
        dataset.dropna(inplace=True)

        j = 0
        for i in range(0, dataset1.shape[0]):
                if dataset1['SITE_NAME'][i] == request.GET.get('site'):
                        dataset.loc[j] = dataset1.iloc[i]
                        j += 1
        dataset.drop(['SITE_NAME'], axis=1, inplace=True)

        dataset['MONSOON'] = (dataset['MONSOON']).apply(np.float64)
        dataset['POMRB'] = (dataset['POMRB']).apply(np.float64)
        dataset['POMKH'] = (dataset['POMKH']).apply(np.float64)
        dataset['PREMON'] = (dataset['PREMON']).apply(np.float64)
        dataset['YEAR_OBS'] = (dataset['YEAR_OBS']).apply(np.int64)

        first = list(dataset['MONSOON'])
        second = list(dataset['POMRB'])
        third = list(dataset['POMKH'])
        fourth = list(dataset['PREMON'])
        dataset['MONSOON'] = pd.core.frame.DataFrame(x + y + z + w for x, y, z, w in zip(first, second, third, fourth))
        dataset.drop(['POMRB', 'POMKH', 'PREMON'], axis=1, inplace=True)
        dataset = dataset.iloc[::-1]

        years = dataset['YEAR_OBS']
        dataset['YEAR_OBS'] = pd.to_datetime(dataset['YEAR_OBS'], yearfirst=True, format='%Y', infer_datetime_format=True)
        indexedDataset = dataset.set_index(['YEAR_OBS'])

        indexedDataset_logscale = np.log(indexedDataset)
        # for i in range(0,indexedDataset_logscale.shape[0]):
        #     if indexedDataset_logscale['MONSOON'][i]<=0:
        #         indexedDataset_logscale['MONSOON'][i]=None
        indexedDataset_logscale.dropna(inplace=True)

        dlds=indexedDataset_logscale-indexedDataset_logscale.shift()
        dlds.dropna(inplace=True)

        import itertools
        a={}
        p=d=q=range(0,6)
        pdq=list(itertools.product(p,d,q))
        for i in pdq:
            try:
                model_arima=(ARIMA(indexedDataset_logscale,order=i)).fit(disp=0)
                a[i]=model_arima.aic
            except:
                continue
        min(a, key=a.get)

        RSS=[]
        RSS1=[]
        ord=[]
        ord1=[]
        for i,j in a.items():    
            model = ARIMA(indexedDataset_logscale, order=i)
            results_ARIMA = model.fit(disp=-1)
            RSS.append(sum((results_ARIMA.fittedvalues-dlds['MONSOON'])**2))
            ord.append(i)
        for i in range(0,len(RSS)):
            if(~np.isnan(RSS[i])):
                RSS1.append(RSS[i])
                ord1.append(ord[i])
        try:
            m=min(RSS1)
        except:
            return "Algorithm Crashed!"
        for i in range(0,len(RSS1)):
            if(RSS1[i]==m):
                req=ord1[i]
                break

        model = ARIMA(indexedDataset_logscale, order=(req[0],req[1],req[2]))
        # try:
        #         model = ARIMA(indexedDataset_logscale, order=(5,1,2))
        # except:
        #         return "Algorithm Crashed!"
        results_ARIMA = model.fit(disp=-1)

        a = list(np.exp(results_ARIMA.forecast(steps=int(request.GET.get('year'))-2016)[0]))

        x2 = []
        for i in range(0, len(a)):
                t = date(int(2017+i),1,i%31+1)
                x2.append([time.mktime(t.timetuple()),a[i]])
        print(x2)

        x1 = []
        y = years.shape[0]-1
        for i in range(0, indexedDataset.shape[0]):

Django WaterIO/templates/basic_app/dropdown.html
<option value="">---</option>
{% for site in sites %}
    <option value="{{ site }}">{{ site }}</option>
{% endfor %}

Django WaterIO/templates/basic_app/forecast.html
{{ gwl1 }}
{{ gwl2 }}
{{ gwl3 }}

Django WaterIO/templates/basic_app/groundwaterlevel.html
<!doctype html>
{% load static from staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Wendy+One" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <title>Water.IO</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image">
    
    <style>
      #header{
/*        background-image: url("C:\Users\Mahe\Desktop\header.jpg") center center / cover no-repeat;*/
        background-image: url("{% static 'images/header.jpg' %}");
        font-family: 'Wendy One', sans-serif;
/*        background: #a8e5ef;*/
      }
      hr.new{
        border: 1px solid black;
      }
      .fo{
        color:#007bff;
        font-size: 20px;
      }
      footer{
        background: black;
        color: white;
      }
      #text{
        display: none;
        font-size: 10vw;
        font-family: 'Wendy One', sans-serif;
      }
      #text2{
        display: none;
        font-size: 8vw;
        font-family: 'Wendy One', sans-serif;
      }
      #chartContainer{
        height: 300px;
        width: 100%;
        display:none
      }
    </style>
  </head>

  <body>
    <nav class="navbar bg-dark fo navbar-expand-sm">
      <a href="{% url 'app:page_one' %}" class="navrbar-brand my-auto ml-5"><i class="fas fa-tint mr-2"></i>Water.IO</a>
      <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="justify-content: flex-end">
        {% comment %} <img src="{% static 'images/favicon.ico' %}" alt="Water_Drop"> {% endcomment %}
        <a href="{% url 'app:user_details' %}" class="nav-item nav-link active" style="text-align:right;><i class="fas fa-id-badge mr-2"></i>{{ user.username }}</a>
        <a href="{% url 'logout' %}" class="nav-item nav-link active" style="text-align:right;><i class="fas fa-user-check mr-2"></i>Logout</a>
      </div>        
    </nav>

    <div id="header" class="jumbotron text-center">
      <h1 class="display-3"><b>Ground Water Level</b></h1>
      <hr class="new" />
    </div>

    <div class="container">
      <form id="personForm" data-sites-url="{% url 'app:ajax_load_sites' %}" action="" method="POST">
        {% csrf_token %}
        {{ form1|crispy }}
        {{ form2|crispy }}
        {{ form3|crispy }}
        <button class="btn btn-primary" type="button" id="model" data-model-url="{% url 'app:ajax_forecast' %}" onclick="myFunction()">Submit</button>
        <br><br>
        <label class="text-center" id="text"><b>Processing...</b></label>
        <label class="text-center" id="text2"><b>Processing Failed...</b></label>
        <br><br>
      </form>
    </div>

    <div class="container pl-0 pl-md-auto" id="chartContainer"></div>

    <p class="py-3"></p>
    <footer class="page-footer font-small pt-2">
      <div class="container text-center text-md-left">
        <div class="row">
          <div class="col-md-3 col-lg-3 mr-auto mt-md-4 my-0 mt-4 mb-0 pl-md-0 pl-lg-auto">
            <h5 class="font-weight-bold text-uppercase mb-4">About</h5>
            <p class="mb-1 mb-md-auto"><b>Released on:</b> 30/04/2019</p>
            <p class="mb-1 mb-md-auto"><b>Tools used:</b> Python, Django, ML, HTML, CSS, Javascript, AJAX</p>
          </div>
          <div class="col-md-2 col-lg-2 mx-auto mt-md-4 my-0 mt-4 mb-0 pl-md-0 pl-lg-auto">
            <h5 class="font-weight-bold text-uppercase mb-4">Developer</h5>
            <ul class="list-unstyled">
              <li><p class="mb-1 mb-md-auto">Rohit P. Jain</p></li>
              <li><p class="mb-1 mb-md-auto">SE-IT</p></li>
            </ul>
          </div>
          <div class="col-md-3 col-lg-2 mx-auto mt-md-4 my-0 mt-4 mb-0 pl-md-4 pl-lg-auto">
            <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>
            <ul class="list-unstyled">
              <li><p class="mb-1 mb-md-auto"><i class="fas fa-home mr-2"></i>DJSCOE, Mumbai</p></li>
            </ul>
          </div>
          <div class="col-md-4 col-lg-3 text mx-auto mt-4 mb-0 pl-md-0 pl-lg-auto">
            <h5 class="font-weight-bold text-uppercase mb-4">Contact Us</h5>
            <p class="mb-1 mb-md-auto"><i class="fab fa-google-plus-g mr-2"></i>rohitrocks2801@gmail.com</p>
            <p class="mb-1 mb-md-auto"><i class="fas fa-phone mr-3"></i>8850237301</p>
          </div>
        </div>
      </div>
      <hr class="m-0 mt-2 d-md-none" style="background:white;">
      <div class="footer-copyright text-center py-2">© 2019 Copyright</div>
    </footer>

    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.0.js" integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

  <script>
    $("#id_block").change(function () {
      {% comment %} console.log('idhar hai apan log') {% endcomment %}
      var url = $("#personForm").attr("data-sites-url");                // get the url of the `load_sites` view
      var blockId = $(this).val();                                      // get the selected block ID from the HTML input
      console.log($("#id_block").val())
      $.ajax({                                                          // initialize an AJAX request
        url: url,                                                       // set the url of the request (= localhost:8000/basic_app/ajax/load-sites/)
        data: {
          'block': blockId                                              // add the block id to the GET parameters
        },
        success: function (data) {                                      // `data` is the return of the `load_sites` view function
          $("#id_site").html(data);                                     // replace the contents of the site input with the data that came from the server
        }
      });
    });

    function myFunction(){
      chartContainer.style.display = "none";
      text2.style.display = "none";
      text.style.display = "block";
      window.scrollBy(0, 100);
      var url = $("#model").attr("data-model-url");
      console.log(url)
      $.ajax({
        url: url,
        data: {
          'block': $("#id_block").val(),
          'site': $("#id_site").val(),
          'year': $("#id_year").val()
        },
        success: function (data) {
          data = data.split('a')
          console.log(data);
          data1 = JSON.parse(data[0])
          data2 = JSON.parse(data[1])
          window.gwl1 = [];
          for (var i=0;i<data1.length;i++){
            var g = {
              x: new Date(data1[i][0]*1000),
              y: data1[i][1]
            }
            gwl1.push(g)
          }
          console.log(gwl1)
          window.gwl2 = [];
          for (var i=0;i<($("#id_year").val()-2016);i++){
            var g = {
              x: new Date(data2[i][0]*1000),
              y: data2[i][1]
            }
            gwl2.push(g)
          }
          console.log(gwl2)
          graph();
        },
        error: function(){
          text.style.display = "none";
          text2.style.display = "block";
        }
      });
    };

    graph = function () {
      text.style.display = "none";
      text2.style.display = "none";
      chartContainer.style.display = "block";
      window.scrollBy(0, 200);
      var chart = new CanvasJS.Chart("chartContainer", {
        animationEnabled: true,
        theme: "light2",
        title:{
          text: "Ground Water Level"
        },
        axisX:{
          title: "Year",
          valueFormatString: "YYYY",
          crosshair: {
            enabled: true,
            snapToDataPoint: true
          }
        },
        axisY: {
          title: "Level",
          crosshair: {
            enabled: true
          }
        },
        toolTip:{
          shared:true
        },
        legend:{
          cursor:"pointer",
          verticalAlign: "bottom",
          horizontalAlign: "left",
          dockInsidePlotArea: true,
          itemclick: toogleDataSeries
        },
        data: [{
          type: "line",
          showInLegend: true,
          name: "Actual Data",
          markerType: "square",
          xValueFormatString: "YYYY",
          color: "#F08080",
          dataPoints: gwl1
          {% comment %} dataPoints: [
            { x: new Date(2017, 0, 3), y: 650 },
            { x: new Date(2017, 0, 4), y: 700 },
            { x: new Date(2017, 0, 5), y: 710 },
            { x: new Date(2017, 0, 6), y: 658 },
            { x: new Date(2017, 0, 7), y: 734 },
            { x: new Date(2017, 0, 8), y: 963 },
            { x: new Date(2017, 0, 9), y: 847 },
            { x: new Date(2017, 0, 10), y: 853 },
            { x: new Date(2017, 0, 11), y: 869 },
            { x: new Date(2017, 0, 12), y: 943 },
            { x: new Date(2017, 0, 13), y: 970 },
            { x: new Date(2017, 0, 14), y: 869 },
            { x: new Date(2017, 0, 15), y: 890 },
            { x: new Date(2017, 0, 16), y: 930 }
          ] {% endcomment %}
        },
        {
          type: "line",
          showInLegend: true,
          name: "Predicted Data",
          lineDashType: "dash",
          xValueFormatString: "YYYY",
          dataPoints: gwl2
          {% comment %} dataPoints: [
            { x: new Date(2017, 0, 3), y: 510 },
            { x: new Date(2017, 0, 4), y: 560 },
            { x: new Date(2017, 0, 5), y: 540 },
            { x: new Date(2017, 0, 6), y: 558 },
            { x: new Date(2017, 0, 7), y: 544 },
            { x: new Date(2017, 0, 8), y: 693 },
            { x: new Date(2017, 0, 9), y: 657 },
            { x: new Date(2017, 0, 10), y: 663 },
            { x: new Date(2017, 0, 11), y: 639 },
            { x: new Date(2017, 0, 12), y: 673 },
            { x: new Date(2017, 0, 13), y: 660 },
            { x: new Date(2017, 0, 14), y: 562 },
            { x: new Date(2017, 0, 15), y: 643 },
            { x: new Date(2017, 0, 16), y: 570 }
          ] {% endcomment %}
        }]
      });
      chart.render();
      console.log(chart.data[0]['dataPoints'])
      console.log(chart.data[1]['dataPoints'])
      function toogleDataSeries(e){
        if (typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
          e.dataSeries.visible = false;
        } else{
          e.dataSeries.visible = true;
        }
        chart.render();
      }
    }
    </script>
</html>